config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => {:registrations => "registrations"}

    namespace :api do
    #devise_for :users, :controllers => {:sessions => "api/sessions", :registrations => "api/registrations"}
        devise_scope :user do
            post '' => "sessions#create"
        end
    end

    # only have update, since other account views are not needed
    resources :accounts, :only => [:update]

    resources :users
    resources :devise

    # routes for the upper task bar
    get 'notice', :to => redirect("/notice.html.erb")
    get 'accounts' => "users#accounts"
    get 'transfers' => "users#transfers"
    get 'withdrawals' => "users#withdrawals"
    get 'deposits' => "users#deposits"
    get 'interests_and_penalties' => "users#interests_and_penalties"
    get 'create' => "users#create_account"
    get 'close_account' => "users#close_account"

    # routes for errors controller
#    get '/404' => 'errors#not_found'
#    get '/422' => 'errors#server_error'
##    get '/500' => 'errors#server_error'
#get '*path', :to => 'errors#not_found'

    # have the default of the site be user's index
    root 'users#index'
end

app/views/shared/_header.html.erb
<head>
    <meta charset="utf-8">
    <title>GoWild! Banking</title>

    <link href="http://s3.amazonaws.com/codecademy-content/courses/ltp2/css/bootstrap.min.css" rel="stylesheet">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <%= stylesheet_link_tag "style.css" %>
</head>

app/views/shared/_upper_bar.html.erb
<div class = "header" style="height: 130px">
  <div class ="logo">
      <a href="http://54.68.34.231/"><img src="/images/logo3.png" style="width: 120px; height: 90px; margin-left:40px;
          margin-top:20px"></a>
  </div>

  <div class ="login info" style="text-align: right">
      <% if user_signed_in? %>
        <% if current_user.account_type == "teller" %>
            <%= sprintf("Thanks for the awesome work, %s %s!",
                        current_user.first_name, current_user.last_name)%>
        <% else %>
            <%= sprintf("Welcome, user %s %s!",
                        current_user.first_name, current_user.last_name)%>
        <% end %>
      <% end %>
  </div>
</div>

<div class = "bar">
<nav class="navbar navbar-inverse">

    <% if not user_signed_in? %>
        <div class="container-fluid">
            <ul class="nav nav-pills">
                <li role="presentation"><%= link_to('SIGNUP', new_user_registration_path)%></a></li>
                <li role="presentation"><%= link_to('LOGIN', new_user_session_path)%></a></li>
            </ul>
        </div>
    <% elsif current_user.account_type == "user"  %>
        <div class="container-fluid">
            <ul class="nav nav-pills">
                <li role="presentation"><%= link_to('ACCOUNTS', accounts_path)%></a></li>
                <li role="presentation"><%= link_to('TRANSFERS', transfers_path)%></a></li>
                <li role="presentation"><%= link_to('WITHDRAWALS', withdrawals_path)%></a></li>
                <li role="presentation"><%= link_to('CLOSE ACCOUNTS', close_account_path)%></a></li>
                <li role="presentation"><%= link_to('LOGOUT', destroy_user_session_path)%></a></li>
            </ul>
        </div>
    <% else %>
        <div class="container-fluid">
            <ul class="nav nav-pills">
                <li role="presentation"><%= link_to('CREATE', create_path)%></a></li>
                <li role="presentation"><%= link_to('ACCOUNTS', accounts_path)%></a></li>
                <li role="presentation"><%= link_to('TRANSFERS', transfers_path)%></a></li>
                <li role="presentation"><%= link_to('DEPOSITS', deposits_path)%></a></li>
                <li role="presentation"><%= link_to('WITHDRAWALS', withdrawals_path)%></a></li>
                <li role="presentation"><%= link_to('INTERESTS/PENALTIES', interests_and_penalties_path)%></a></li>
                <li role="presentation"><%= link_to('CLOSE ACCOUNTS', close_account_path)%></a></li>
                <li role="presentation"><%= link_to('LOGOUT', destroy_user_session_path)%></a></li>
            </ul>
        </div>
    <% end %>

</nav>
</div>